name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    #runs-on: zeoneo/zeonos_build:latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install toolchain
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        wget -qO - https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 | tar -xjf -
        ls -al ./gcc-arm-none-eabi-10.3-2021.10/bin/

    - name: Build
      # Build your program with the given configuration
      run: |
        export SHELL=/bin/bash
        export PATH=./gcc-arm-none-eabi-10.3-2021.10/bin/:${PATH}
        echo "export PATH=\$PATH:\$(pwd)/gcc-arm-none-eabi-10.3-2021.10/bin/" >> $HOME/.profile && source $HOME/.profile
        mkdir zeonos_build
        cd zeonos_build
        cmake ..
        make VERBOSE=1
